//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class URUNSTOKPROJEDBEntities : DbContext
    {
        public URUNSTOKPROJEDBEntities()
            : base("name=URUNSTOKPROJEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_kategoriler> TBL_kategoriler { get; set; }
        public virtual DbSet<TBL_musteriler> TBL_musteriler { get; set; }
        public virtual DbSet<TBL_satislar> TBL_satislar { get; set; }
        public virtual DbSet<TBL_urunler> TBL_urunler { get; set; }
    }
}
