//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_urunler()
        {
            this.TBL_satislar = new HashSet<TBL_satislar>();
        }
    
        public int urunid { get; set; }
        public string urunad { get; set; }
        public Nullable<short> urunkategori { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string marka { get; set; }
    
        public virtual TBL_kategoriler TBL_kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_satislar> TBL_satislar { get; set; }
    }
}
